version: '3.8'

services:
  mysql:
    image: mysql:8.0.38
    container_name: waggle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - waggle-network
    restart: unless-stopped

  app:
    build: .
    container_name: waggle-app
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      DB_HOST: ${DB_HOST:-waggle-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PORT:-9008}:9008"
    networks:
      - waggle-network
    restart: unless-stopped
    # 헬스체크 추가
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9008/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  waggle-network:
    driver: bridge
